version: 2.1
orbs:
  slack: circleci/slack@3.4.1

jobs:
  sandbox:
    executor:
      name: slack/alpine
    steps:
      - slack/notify:
          message: "Hello, world"
  sandbox2:
    executor:
      name: slack/alpine
    steps:
      - slack/notify:
          message: "OK!"

workflows:
  version: 2
  workflow-test:
    jobs:
      - sandbox
      - sandbox2
